### PR TITLE
Use with Docker

### PR DESCRIPTION
**Pull request by kylegordon**
I've taken some inspiration from https://hub.docker.com/r/derjudge/projectsend/ but I disagree with running git clone as part of the docker run stage. After the docker build process, no data should change within an image layer. Anything that changes should be temporary, or as part of a volume.

This Dockerfile will make a static docker image that does not require any git cloning or changing of data during startup. 

It will call upon an external database of the users choosing, and it also makes provision for persistent storage for uploaded files, in the event the docker images is upgraded or started from fresh but with an existing database. 

If you have a hub.docker.com account, please change the example and the Dockerfile to suit. 

A fresh docker image can be built with a command similar to following
git clone https://github.com/kylegordon/ProjectSend/
cd ProjectSend
docker build . -t kylegordon/projectsend:r756
docker push kylegordon/projectsend:r756

Have I missed anything? :-)

### CODE REVIEW

**Comment by ignacionelson** [comment]
I'm sorry that I still didn't merge this one. I will review it as soon as possible and merge. Thanks for your hard work!!

**Comment by ignacionelson** [comment]
Thanks for all your hard work! I want to merge this badly!!!
Just one question.
On the readme, your example ends with kylegordon/projectsend:r756
Can you please tell me why?
Thanks!!

**Comment by ignacionelson** [comment]
Hi Kyle! Have you seen my message? Please let me know. Thanks!

**Comment by stavros-k** [comment]
> I'm sorry that I still didn't merge this one. I will review it as soon as possible and merge. Thanks for your hard work!!

Sorry for the rush, Did you manage to review it?

**Pull request closed without merging**
