### PR TITLE
Spellcheck pass

### PR DESCRIPTION
**Pull request by ehawman-rosenberg**
Downloaded Code Spell Checker for VSCode and played around with it on ProjectSend. 

1. Code Spell Checker highlighted an issue.
2. I validate that it's a spelling issue, not a false positive (`xsendfile` isn't in the dictionary, but it isn't a misspelling).
3. Replaced all instances of spelling error in all files.
4. Repeat 1-3 until there are no more issues.
5. Manually confirm all changes before commit.

There was only 1 spelling error in a variable (duplicated in two places), and that was `$rediret_to`. The others were all either comments or strings.

### CODE REVIEW

**Comment by ehawman-rosenberg** [comment]
I'm new to Git, so I borked continuity by a hair. I was going to test rebuilding a function before I got sidetracked with spellcheck, and as a result I had to snip it back out. My house is in order now :)

**Comment by ehawman-rosenberg** [comment]
Oh and I added .vscode to .gitignore.

**Comment by ignacionelson** [comment]
Thank you!
I even misspelled the app's name, that's embarrassing!

**Comment by ehawman-rosenberg** [comment]
Happens to everybody! If I had to spell rediculous... rideculus... **_ridiculous_** without spellcheck I'd be doomed.

**Pull request merged**
