### PR TITLE
add custom link functionality

### PR DESCRIPTION
**Pull request by mhpcc**
(can be setup through a different vhost or rewriterule to generate shorter custom links)

#eb199ad
#9925896
#b4e0b33
are bug fixes

### CODE REVIEW

**Comment by ignacionelson** [comment]
This is great! I'll merge ASAP

**Comment by mhpcc** [comment]
good to hear, translations are still missing (I wasn't sure how to do those) and for the future there should be an edit form for the links, but we needed the functionality quick

**Comment by ignacionelson** [comment]
Thanks!
I'll be doing a few UI changes to better explain how this feature works (mainly adding notes under the custom download url in the options panel and the field in the file editor.
But I'm a bit lost at that part. I'm not sure why you can set multiple aliases for the same file.

**Comment by mhpcc** [comment]
> But I'm a bit lost at that part. I'm not sure why you can set multiple aliases for the same file.

One example for which we use it is: 

/c/General_terms_and_services
and
/c/General_terms_and_services_2023_02_01

both linking to the same file right now. If we want a permalink to the current version, /c/General_terms_and_services will be updated in the future, if we want a permalink to the February 2023 version, the latter one can be used.

**Pull request merged**
