### PR TITLE
Add basic slim setup including di setup

### PR DESCRIPTION
**Pull request by mschop**
HI @ignacionelson ,

this PR implements the rough slim & di setup structure including a first HelloWorldController. I could not test it, because there were many things that are not working in the refactor branch right now. Either merge and fix the problems or fix the problem and inform me. Then I could rebase my changes on your fixes.

Best Regards
mschop

### CODE REVIEW

**Review by ignacionelson — COMMENTED** [review]
Great to have something to start with!
One question, why would you require php 7.0? It seems that slim is Ok with 5.6.
I believe that php 7 as a requirement would greatly limit the user base.

**Comment by mschop** [comment]
Well PHP < 7.1 will only be officially supported until January 2019. See http://php.net/supported-versions.php . I think it does not make any sense to support versions before 7.0. PHP 7.0 introduced type hints for scalars (parameter and return types) and has a lot of other improvements. When doing such great refactoring I think one can drop support for old version and profit from those improvements instead.

Most hoster support PHP > 7.0 and the user should simply update to a new PHP version. Furthermore you could provide the old version as a LTS release, where only critical bug fixes or security fixes are added.

**Comment by ignacionelson** [comment]
I get your point. I do however find a little aggressive to not support a version that is currently still the minimum required for so much of popular web applications.
I also think that most installations of PS are most probably not the main app of a certain domain, but a helper running on the side of a CMS or a simple site. In those cases, PS would be forcing the main software to use another php version which might not be supported. I myself have WP sites that cannot be updated due to, for example, irreplaceable plugins that do not have a compatible version yet.

Maybe there is a way to still support php 5.6 by providing fallbacks. Of course, this is just an opinion and something to discuss about.

**Comment by ignacionelson** [comment]
I will merge the PR and lower the req just for now, would that be ok?

**Comment by mschop** [comment]
sure thats absolutely ok. Don't forget to remove the typehints and add phpdocs instead

**Pull request merged**
