### PR TITLE
Password for public download + 3 patch from evcwally

### PR DESCRIPTION
**Pull request by fab120**
New function:
Password for public download: you can set up a password for a public download.

Other Patch:
Update upload-import-orphans.php (from evcwally)
Update file-upload.php (from evcwally)
Update core.update.php (from evcwally)

Thanks to
evcwally
Diego Verì (@Snake231088)

### CODE REVIEW

**Comment by ignacionelson** [comment]
I absolutely LOVE the password for public files idea.
However, it seems like passwords are being saved without encryption. Will need to adjust to at least use md5 or another method before saving/reading.

**Comment by fab120** [comment]
Finally after an exact year :D

I choose to save the password without encryption because it doesn't let you access to any sensitive data. If your file contains sensitive data maybe a web solution is not the right choice to share it...

Anyway (in this case) the password should be thinked as a code; a deterrent to avoid that people who casually visit the page can download the file. Like a complex url that can avoid people to casually visit  the page :D

But we both know that users will use the same password that they are using in their email account -_-'

I will try to implement it as soon as i can :)

**Comment by wdmtech** [comment]
Just to chip in:

Passwords must **always** be encrypted to protect users. There is no excuse for not encrypting passwords.

**Comment by ignacionelson** [comment]
I agree. We can reuse the phpass library here. It's used for the main accounts passwords and it's REALLY easy to implement.

**Comment by Costly** [comment]
was this ever merged into the current release?

**Pull request closed without merging**
