### PR TITLE
Added chunked download of file with resume in pure php

### PR DESCRIPTION
**Pull request by jensbrand**
Because I cannot use XSendFile on my webserver I've refactored the file download in pure php. Now it is possible to pause and resume a download, which is extreme nice for big files.

### CODE REVIEW

**Comment by ignacionelson** [comment]
Thank you!!

**Comment by alexschomb** [comment]
Hi, thanks for your contribution. Unfortunately I just noticed that it breaks downloads completely for existing installations that have `X-Accel (nginx)` selected in the options. Does the new PHP chucked download method replace the previous Apache and nginx methods as well? If that is the case the option should be completely removed from the settings.

**Comment by ignacionelson** [comment]
@alexschomb Hi! I've tested this with nginx and x-accel and had no issues. Are you sure this is the commit that broke your installation? The code is wrapped on a switch function so only php downloads should be affected.

**Comment by alexschomb** [comment]
Hi @ignacionelson, thanks for your feedback. Honestly, I'm not definitely sure that this was the issue, because I'm running ProjectSend with [this Docker image](https://github.com/linuxserver/docker-projectsend). I upgraded my existing installation and noticed that I couldn't download anything, when I switched the option to `php` downloads it worked. Before, I was using the `nginx` option.

**Pull request merged**
